name: SWAPI Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: [
          "__test__/test_planets.js",                 # Testes de Planetas
          "__test__/test_specific_planet.js",         # Testes de um planeta específico
          "__test__/test_starships.js",               # Testes de Naves
          "__test__/test_specific_starship.js",       # Testes de uma nave específica
          "__test__/test_films.js",                   # Testes de Filmes
          "__test__/test_specific_film.js",           # Testes de um filme específico
          "__test__/test_people.js",                  # Testes de Pessoas
          "__test__/test_specific_character.js",      # Testes de um personagem específico
          "__test__/test_invalid_route.js",           # Testes de rota inválida
          "__test__/test_nonexistent_resource.js"     # Testes de recurso inexistente
        ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - name: Run Jest test
        run: npm test ${{ matrix.file }}
