name: SWAPI Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: [
          "__tests__/test_planets.js",                    # Teste de planetas
          "__tests__/test_specific_planet.js",            # Teste de um planeta específico
          "__tests__/test_starships.js",                  # Teste de naves
          "__tests__/test_specific_starship.js",          # Teste de uma nave específica
          "__tests__/test_films.js",                      # Teste de filmes
          "__tests__/test_specific_film.js",              # Teste de um filme específico
          "__tests__/test_people.js",                     # Teste de personagens
          "__tests__/test_specific_character.js",        # Teste de um personagem específico
          "__tests__/test_invalid_route.js",              # Teste de rota inválida
          "__tests__/test_nonexistent_resource.js"        # Teste de recurso inexistente
        ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - name: Run Jest tests
        run: npm test ${{ matrix.file }}
