name: SWAPI Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: [
          "tests/planets.test.js",
          "tests/specific_planet.test.js",
          "tests/starships.test.js",
          "tests/specific_starship.test.js",
          "tests/films.test.js",
          "tests/specific_film.test.js",
          "tests/people.test.js",
          "tests/specific_character.test.js",
          "tests/invalid_route.test.js",
          "tests/nonexistent_resource.test.js"
        ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - name: Run Jest test
        run: npm test ${{ matrix.file }}
